/// Demo data for Materials/Product Master page - matches React app's mock data
class MaterialsDemo {
  MaterialsDemo._();

  static List<Map<String, dynamic>> get materials => [
    {
      'material_id': 'MAT-001',
      'code': 'MAT-001',
      'name': 'Cement OPC 53',
      'category': 'Civil',
      'unit': 'Bags',
      'stock': 500.0,
      'min_stock': 100.0,
      'max_stock': 2000.0,
      'unit_price': 350.0,
      'location': 'Main Warehouse',
    },
    {
      'material_id': 'MAT-002',
      'code': 'MAT-002',
      'name': 'PVC Pipe 4"',
      'category': 'Plumbing',
      'unit': 'Meters',
      'stock': 200.0,
      'min_stock': 250.0,
      'max_stock': 1000.0,
      'unit_price': 120.0,
      'location': 'Main Warehouse',
    },
    {
      'material_id': 'MAT-003',
      'code': 'MAT-003',
      'name': 'Steel TMT 12mm',
      'category': 'Civil',
      'unit': 'KG',
      'stock': 1500.0,
      'min_stock': 500.0,
      'max_stock': 5000.0,
      'unit_price': 65.0,
      'location': 'Main Warehouse',
    },
    {
      'material_id': 'MAT-004',
      'code': 'MAT-004',
      'name': 'Electrical Cable 2.5mm',
      'category': 'Electrical',
      'unit': 'Meters',
      'stock': 800.0,
      'min_stock': 200.0,
      'max_stock': 3000.0,
      'unit_price': 18.0,
      'location': 'Secondary Store',
    },
    {
      'material_id': 'MAT-005',
      'code': 'MAT-005',
      'name': 'River Sand',
      'category': 'Civil',
      'unit': 'CFT',
      'stock': 80.0,
      'min_stock': 150.0,
      'max_stock': 500.0,
      'unit_price': 45.0,
      'location': 'Overflow Storage',
    },
    {
      'material_id': 'MAT-006',
      'code': 'MAT-006',
      'name': 'CPVC Pipe 1"',
      'category': 'Plumbing',
      'unit': 'Meters',
      'stock': 450.0,
      'min_stock': 100.0,
      'max_stock': 800.0,
      'unit_price': 85.0,
      'location': 'Main Warehouse',
    },
    {
      'material_id': 'MAT-007',
      'code': 'MAT-007',
      'name': 'MS Pipe 2"',
      'category': 'Fire Fighting',
      'unit': 'Meters',
      'stock': 320.0,
      'min_stock': 100.0,
      'max_stock': 600.0,
      'unit_price': 210.0,
      'location': 'Main Warehouse',
    },
    {
      'material_id': 'MAT-008',
      'code': 'MAT-008',
      'name': 'GI Wire 16 Gauge',
      'category': 'Civil',
      'unit': 'KG',
      'stock': 90.0,
      'min_stock': 50.0,
      'max_stock': 300.0,
      'unit_price': 75.0,
      'location': 'Secondary Store',
    },
    {
      'material_id': 'MAT-009',
      'code': 'MAT-009',
      'name': 'Copper Pipe 15mm',
      'category': 'HVAC',
      'unit': 'Meters',
      'stock': 150.0,
      'min_stock': 50.0,
      'max_stock': 400.0,
      'unit_price': 320.0,
      'location': 'Main Warehouse',
    },
    {
      'material_id': 'MAT-010',
      'code': 'MAT-010',
      'name': 'Teflon Tape',
      'category': 'Plumbing',
      'unit': 'Rolls',
      'stock': 250.0,
      'min_stock': 50.0,
      'max_stock': 500.0,
      'unit_price': 25.0,
      'location': 'Secondary Store',
    },
    {
      'material_id': 'MAT-011',
      'code': 'MAT-011',
      'name': 'Aggregate 20mm',
      'category': 'Civil',
      'unit': 'CFT',
      'stock': 350.0,
      'min_stock': 200.0,
      'max_stock': 1000.0,
      'unit_price': 38.0,
      'location': 'Overflow Storage',
    },
    {
      'material_id': 'MAT-012',
      'code': 'MAT-012',
      'name': 'Sprinkler Head',
      'category': 'Fire Fighting',
      'unit': 'Nos',
      'stock': 45.0,
      'min_stock': 100.0,
      'max_stock': 500.0,
      'unit_price': 450.0,
      'location': 'Main Warehouse',
    },
  ];
}
