/// Demo data for Vendors page - matches React app's mock data
class VendorsDemo {
  VendorsDemo._();

  static List<Map<String, dynamic>> get vendors => [
    {
      'vendor_id': 'VND-001',
      'name': 'ABC Suppliers Pvt Ltd',
      'contact_person': 'Rajesh Kumar',
      'phone': '9876543210',
      'email': 'rajesh@abcsuppliers.com',
      'address': '123 Industrial Area, Andheri East, Mumbai 400069',
      'status': 'Active',
      'type': 'Vendor',
      'rating': 4.5,
      'gst_no': '27AABCU9603R1ZM',
      'pan_no': 'AABCU9603R',
    },
    {
      'vendor_id': 'VND-002',
      'name': 'XYZ Traders',
      'contact_person': 'Priya Sharma',
      'phone': '9876543211',
      'email': 'priya@xyztraders.com',
      'address': '45 MG Road, Pune 411001',
      'status': 'Active',
      'type': 'Vendor',
      'rating': 4.0,
      'gst_no': '27AABCX1234R1ZN',
      'pan_no': 'AABCX1234R',
    },
    {
      'vendor_id': 'VND-003',
      'name': 'Metro Steel Works',
      'contact_person': 'Amit Patel',
      'phone': '9123456789',
      'email': 'amit@metrosteel.in',
      'address': '78 MIDC, Bhosari, Pune 411026',
      'status': 'Active',
      'type': 'Vendor',
      'rating': 4.8,
      'gst_no': '27AABCM5678R1ZP',
      'pan_no': 'AABCM5678R',
    },
    {
      'vendor_id': 'VND-004',
      'name': 'Reliable Electricals',
      'contact_person': 'Suresh Menon',
      'phone': '9988776655',
      'email': 'info@reliableelectricals.com',
      'address': '56 Lamington Road, Mumbai 400004',
      'status': 'Active',
      'type': 'Vendor',
      'rating': 3.8,
      'gst_no': '27AABCR9012R1ZQ',
      'pan_no': 'AABCR9012R',
    },
    {
      'vendor_id': 'VND-005',
      'name': 'Sunrise Plumbing Solutions',
      'contact_person': 'Deepak Verma',
      'phone': '9112233445',
      'email': 'deepak@sunriseplumbing.in',
      'address': '22 Nariman Point, Mumbai 400021',
      'status': 'Active',
      'type': 'Service Provider',
      'rating': 4.2,
      'gst_no': '27AABCS3456R1ZR',
      'pan_no': 'AABCS3456R',
    },
    {
      'vendor_id': 'VND-006',
      'name': 'National Fire Safety Co.',
      'contact_person': 'Kavita Joshi',
      'phone': '9223344556',
      'email': 'kavita@nationalfire.com',
      'address': '99 Vashi, Navi Mumbai 400703',
      'status': 'Active',
      'type': 'Vendor',
      'rating': 4.6,
      'gst_no': '27AABCN7890R1ZS',
      'pan_no': 'AABCN7890R',
    },
    {
      'vendor_id': 'VND-007',
      'name': 'Green Earth Aggregates',
      'contact_person': 'Rahul Deshmukh',
      'phone': '9334455667',
      'email': 'rahul@greenearth.co.in',
      'address': '12 Hinjewadi, Pune 411057',
      'status': 'Inactive',
      'type': 'Vendor',
      'rating': 3.5,
      'gst_no': '27AABCG4321R1ZT',
      'pan_no': 'AABCG4321R',
    },
    {
      'vendor_id': 'VND-008',
      'name': 'HVAC Systems India',
      'contact_person': 'Neha Kapoor',
      'phone': '9445566778',
      'email': 'neha@hvacsystems.in',
      'address': '33 BKC, Mumbai 400051',
      'status': 'Active',
      'type': 'Service Provider',
      'rating': 4.3,
      'gst_no': '27AABCH8765R1ZU',
      'pan_no': 'AABCH8765R',
    },
  ];
}
