import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'file_service.dart';

/// PDF generation and printing service
class PdfService {
  /// Generate a PDF document
  static Future<pw.Document> createDocument({
    PdfPageFormat pageFormat = PdfPageFormat.a4,
  }) async {
    return pw.Document(
      creator: 'Madhuram App',
      producer: 'Madhuram Construction Management',
    );
  }

  /// Build a standard header for reports
  static pw.Widget buildHeader({
    required String title,
    String? subtitle,
    String? projectName,
    String? date,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 16),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(width: 1, color: PdfColors.grey300)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              if (subtitle != null) pw.SizedBox(height: 4),
              if (subtitle != null) pw.Text(subtitle, style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
              if (projectName != null) pw.SizedBox(height: 8),
              if (projectName != null) pw.Text('Project: $projectName', style: const pw.TextStyle(fontSize: 10)),
            ],
          ),
          if (date != null)
            pw.Text(date, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
        ],
      ),
    );
  }

  /// Build a standard footer
  static pw.Widget buildFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(width: 0.5, color: PdfColors.grey300)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Madhuram', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
        ],
      ),
    );
  }

  /// Build a table
  static pw.Widget buildTable({
    required List<String> headers,
    required List<List<String>> rows,
    List<int>? columnWidths,
  }) {
    return pw.TableHelper.fromTextArray(
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
      cellStyle: const pw.TextStyle(fontSize: 9),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
      cellHeight: 28,
      cellAlignments: Map.fromIterables(
        List.generate(headers.length, (i) => i),
        List.generate(headers.length, (i) => pw.Alignment.centerLeft),
      ),
      headers: headers,
      data: rows,
    );
  }

  /// Build a summary box
  static pw.Widget buildSummaryBox({
    required String title,
    required Map<String, String> items,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          ...items.entries.map((e) => pw.Padding(
            padding: const pw.EdgeInsets.symmetric(vertical: 2),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(e.key, style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
                pw.Text(e.value, style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
              ],
            ),
          )),
        ],
      ),
    );
  }

  /// Save PDF to file
  static Future<File?> saveToFile(pw.Document doc, String filename) async {
    try {
      final bytes = await doc.save();
      return await FileService.saveFile(filename: filename, bytes: bytes, subfolder: 'reports');
    } catch (e) {
      print('Error saving PDF: $e');
    }
    return null;
  }

  /// Share PDF
  static Future<void> sharePdf(pw.Document doc, String filename) async {
    try {
      final bytes = await doc.save();
      final dir = await getTemporaryDirectory();
      final file = File('${dir.path}/$filename');
      await file.writeAsBytes(bytes);
      await FileService.shareFile(file, subject: filename);
    } catch (e) {
      print('Error sharing PDF: $e');
    }
  }

  /// Print PDF
  static Future<bool> printPdf(pw.Document doc) async {
    try {
      return await Printing.layoutPdf(
        onLayout: (format) async => doc.save(),
        name: 'Madhuram Report',
      );
    } catch (e) {
      print('Error printing PDF: $e');
    }
    return false;
  }

  /// Preview PDF
  static Future<void> previewPdf(pw.Document doc) async {
    await Printing.layoutPdf(
      onLayout: (format) async => doc.save(),
    );
  }

  /// Generate BOQ Report
  static Future<pw.Document> generateBOQReport({
    required String projectName,
    required List<Map<String, dynamic>> items,
  }) async {
    final doc = await createDocument();
    final now = DateTime.now();
    final dateStr = '${now.day}/${now.month}/${now.year}';

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => buildHeader(
          title: 'Bill of Quantities',
          subtitle: 'Project Material List',
          projectName: projectName,
          date: dateStr,
        ),
        footer: buildFooter,
        build: (context) => [
          pw.SizedBox(height: 20),
          buildTable(
            headers: ['S.No', 'Item Description', 'Unit', 'Quantity', 'Rate', 'Amount'],
            rows: items.asMap().entries.map((e) => [
              (e.key + 1).toString(),
              (e.value['description'] ?? '').toString(),
              (e.value['unit'] ?? '').toString(),
              (e.value['quantity'] ?? 0).toString(),
              '₹${e.value['rate'] ?? 0}',
              '₹${e.value['amount'] ?? 0}',
            ]).toList(),
          ),
          pw.SizedBox(height: 20),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.end,
            children: [
              buildSummaryBox(
                title: 'Summary',
                items: {
                  'Total Items': items.length.toString(),
                  'Total Amount': '₹${items.fold<num>(0, (sum, item) => sum + (item['amount'] ?? 0)).toStringAsFixed(2)}',
                },
              ),
            ],
          ),
        ],
      ),
    );

    return doc;
  }

  /// Generate Purchase Order PDF
  static Future<pw.Document> generatePurchaseOrderPdf({
    required String poNumber,
    required String vendorName,
    required String projectName,
    required List<Map<String, dynamic>> items,
    required double totalAmount,
    String? terms,
  }) async {
    final doc = await createDocument();
    final now = DateTime.now();
    final dateStr = '${now.day}/${now.month}/${now.year}';

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => buildHeader(
          title: 'Purchase Order',
          subtitle: poNumber,
          projectName: projectName,
          date: dateStr,
        ),
        footer: buildFooter,
        build: (context) => [
          pw.SizedBox(height: 16),
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Vendor', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                    pw.SizedBox(height: 4),
                    pw.Text(vendorName, style: const pw.TextStyle(fontSize: 10)),
                  ],
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 20),
          buildTable(
            headers: ['S.No', 'Description', 'Unit', 'Qty', 'Rate', 'Amount'],
            rows: items.asMap().entries.map((e) => [
              (e.key + 1).toString(),
              (e.value['description'] ?? '').toString(),
              (e.value['unit'] ?? '').toString(),
              (e.value['quantity'] ?? 0).toString(),
              '₹${e.value['rate'] ?? 0}',
              '₹${((e.value['quantity'] ?? 0) * (e.value['rate'] ?? 0)).toStringAsFixed(2)}',
            ]).toList(),
          ),
          pw.SizedBox(height: 20),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.end,
            children: [
              pw.Container(
                width: 200,
                child: pw.Column(
                  children: [
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('Subtotal:', style: const pw.TextStyle(fontSize: 10)),
                        pw.Text('₹${totalAmount.toStringAsFixed(2)}', style: const pw.TextStyle(fontSize: 10)),
                      ],
                    ),
                    pw.SizedBox(height: 4),
                    pw.Divider(),
                    pw.SizedBox(height: 4),
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('Total:', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                        pw.Text('₹${totalAmount.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
          if (terms != null) ...[
            pw.SizedBox(height: 30),
            pw.Text('Terms & Conditions', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
            pw.SizedBox(height: 8),
            pw.Text(terms, style: const pw.TextStyle(fontSize: 9)),
          ],
          pw.SizedBox(height: 50),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                children: [
                  pw.Container(width: 150, height: 1, color: PdfColors.black),
                  pw.SizedBox(height: 4),
                  pw.Text('Authorized Signature', style: const pw.TextStyle(fontSize: 9)),
                ],
              ),
              pw.Column(
                children: [
                  pw.Container(width: 150, height: 1, color: PdfColors.black),
                  pw.SizedBox(height: 4),
                  pw.Text('Vendor Acceptance', style: const pw.TextStyle(fontSize: 9)),
                ],
              ),
            ],
          ),
        ],
      ),
    );

    return doc;
  }

  /// Generate Invoice PDF
  static Future<pw.Document> generateInvoicePdf({
    required String invoiceNumber,
    required String clientName,
    required String projectName,
    required List<Map<String, dynamic>> items,
    required double totalAmount,
    double taxRate = 18.0,
  }) async {
    final doc = await createDocument();
    final now = DateTime.now();
    final dateStr = '${now.day}/${now.month}/${now.year}';
    final taxAmount = totalAmount * (taxRate / 100);
    final grandTotal = totalAmount + taxAmount;

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => buildHeader(
          title: 'Invoice',
          subtitle: invoiceNumber,
          projectName: projectName,
          date: dateStr,
        ),
        footer: buildFooter,
        build: (context) => [
          pw.SizedBox(height: 16),
          pw.Text('Bill To: $clientName', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
          pw.SizedBox(height: 20),
          buildTable(
            headers: ['S.No', 'Description', 'Quantity', 'Rate', 'Amount'],
            rows: items.asMap().entries.map((e) => [
              (e.key + 1).toString(),
              (e.value['description'] ?? '').toString(),
              (e.value['quantity'] ?? 0).toString(),
              '₹${e.value['rate'] ?? 0}',
              '₹${((e.value['quantity'] ?? 0) * (e.value['rate'] ?? 0)).toStringAsFixed(2)}',
            ]).toList(),
          ),
          pw.SizedBox(height: 20),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.end,
            children: [
              pw.Container(
                width: 200,
                child: pw.Column(
                  children: [
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('Subtotal:', style: const pw.TextStyle(fontSize: 10)),
                        pw.Text('₹${totalAmount.toStringAsFixed(2)}', style: const pw.TextStyle(fontSize: 10)),
                      ],
                    ),
                    pw.SizedBox(height: 4),
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('GST ($taxRate%):', style: const pw.TextStyle(fontSize: 10)),
                        pw.Text('₹${taxAmount.toStringAsFixed(2)}', style: const pw.TextStyle(fontSize: 10)),
                      ],
                    ),
                    pw.SizedBox(height: 4),
                    pw.Divider(),
                    pw.SizedBox(height: 4),
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('Grand Total:', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                        pw.Text('₹${grandTotal.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );

    return doc;
  }
}
